kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: docker
    commands:
      - docker build -t short-d/emotic -f backend/Dockerfile backend
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - testing
      ref:
        - refs/tags/test-v*
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock