kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: docker
    commands:
      - cd backend && docker build -t short-d/emotic .
      - docker run short-d/emotic
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - testing
      ref:
        - refs/tags/test-v*